# -*- coding: utf-8 -*-
"""Dice Roll Button Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e9j7s1jhP9gcDTh6rURuGKMn_iZxEe9P
"""

!pip install ipywidgets

import random
import ipywidgets as widgets
from IPython.display import display

import random
import ipywidgets as widgets
from IPython.display import display

# Scores
user_score = 0
computer_score = 0

# Output display
output = widgets.Output()

# Labels
score_label = widgets.Label(value="Score → You: 0 | Computer: 0")
result_label = widgets.Label(value="Click Roll Dice to start!")

# Button
roll_button = widgets.Button(description="🎲 Roll Dice")

def roll_dice(b):
    global user_score, computer_score

    user_roll = random.randint(1, 6)
    computer_roll = random.randint(1, 6)

    if user_roll > computer_roll:
        user_score += 1
        result = "🎉 You Win This Round!"
    elif computer_roll > user_roll:
        computer_score += 1
        result = "💻 Computer Wins This Round!"
    else:
        result = "🤝 It's a Tie!"

    score_label.value = f"Score → You: {user_score} | Computer: {computer_score}"
    result_label.value = f"You rolled {user_roll} | Computer rolled {computer_roll} → {result}"

roll_button.on_click(roll_dice)

display(score_label)
display(result_label)
display(roll_button)