# -*- coding: utf-8 -*-
"""Treasure Hunt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8nffREwcw7g-UjDm32Rwy8ZxFcq3XGI
"""

!pip install ipywidgets

import random
import ipywidgets as widgets
from IPython.display import display

# Game Variables
wins = 0
lives = 3
treasure_door = random.randint(1, 5)
jackpot_door = random.randint(1, 5)

# Labels
score_label = widgets.Label(value="🏆 Wins: 0 | ❤️ Lives: 3")
result_label = widgets.Label(value="Choose a door to find the treasure!")

# Restart Button
restart_button = widgets.Button(description="🔄 Restart Game")
restart_button.layout.visibility = 'hidden'

def end_game():
    for button in door_buttons:
        button.disabled = True
    restart_button.layout.visibility = 'visible'

def restart_game(b):
    global wins, lives, treasure_door, jackpot_door
    wins = 0
    lives = 3
    treasure_door = random.randint(1, 5)
    jackpot_door = random.randint(1, 5)
    score_label.value = "🏆 Wins: 0 | ❤️ Lives: 3"
    result_label.value = "Game Restarted! Choose a door!"
    restart_button.layout.visibility = 'hidden'
    for button in door_buttons:
        button.disabled = False

restart_button.on_click(restart_game)

def choose_door(door_number):
    global wins, lives, treasure_door, jackpot_door

    if lives == 0:
        return

    if door_number == treasure_door:
        if door_number == jackpot_door:
            wins += 2
            result_label.value = f"💰 JACKPOT! Door {door_number}: +2 Points!"
        else:
            wins += 1
            result_label.value = f"🎉 Door {door_number}: You found the treasure!"
    else:
        lives -= 1
        result_label.value = f"💀 Door {door_number}: Trap! Lives left: {lives}"

    score_label.value = f"🏆 Wins: {wins} | ❤️ Lives: {lives}"

    if lives == 0:
        result_label.value = "💀 Game Over! You lost all lives!"
        end_game()
    else:
        treasure_door = random.randint(1, 5)
        jackpot_door = random.randint(1, 5)

# Create Door Buttons
door_buttons = []

for i in range(1, 6):
    button = widgets.Button(description=f"🚪 Door {i}")
    button.on_click(lambda b, door=i: choose_door(door))
    door_buttons.append(button)

# Display
display(score_label)
display(result_label)

for button in door_buttons:
    display(button)

display(restart_button)