# -*- coding: utf-8 -*-
"""Treasure Hunt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8nffREwcw7g-UjDm32Rwy8ZxFcq3XGI
"""

!pip install ipywidgets

import random
import ipywidgets as widgets
from IPython.display import display

# Game variables
wins = 0
losses = 0
treasure_door = random.randint(1, 5)

# Labels
score_label = widgets.Label(value="🏆 Wins: 0 | 💀 Losses: 0")
result_label = widgets.Label(value="Choose a door to find the treasure!")

# Function when door clicked
def choose_door(door_number):
    global wins, losses, treasure_door

    if door_number == treasure_door:
        wins += 1
        result_label.value = f"🎉 Door {door_number}: You found the treasure!"
    else:
        losses += 1
        result_label.value = f"💀 Door {door_number}: Trap! Treasure was behind door {treasure_door}"

    # Update score
    score_label.value = f"🏆 Wins: {wins} | 💀 Losses: {losses}"

    # Reset treasure for next round
    treasure_door = random.randint(1, 5)

# Create 5 door buttons
door_buttons = []

for i in range(1, 6):
    button = widgets.Button(description=f"🚪 Door {i}")
    button.on_click(lambda b, door=i: choose_door(door))
    door_buttons.append(button)

# Display everything
display(score_label)
display(result_label)

for button in door_buttons:
    display(button)